
; Assembly source line config statements

#include "p16f648a.inc"

; CONFIG
; __config 0xFF21
CBLOCK
CUENTA_D
ENDC
   
; CONFIG
; __config 0xFF21
 __CONFIG _FOSC_XT & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _CP_OFF
 
NUMERO EQU D'16'
NUMERO_2 EQU D'10'
	ORG	0
	GOTO	INICIO
	
INICIO
	MOVLW	B'00000111'
	MOVWF	CMCON
	BSF	STATUS,RP0
	CLRF	TRISB
	BSF	TRISA,0
	BCF	TRISA,1
	BCF	TRISA,2
	BCF	STATUS,RP0
	CLRF	CUENTA_D
	BSF	PORTA,1; DISPLAY 1
	BCF	PORTA,2; DISPLAY
START
	MOVF	CUENTA_D,W
	CALL	DISPLAY
	MOVWF	PORTB
	CALL	Retardo_20ms
	CALL	Retardo_20ms
	CALL	Retardo_20ms
	BTFSS	PORTA,0
	GOTO	START
	INCF	CUENTA_D,F
	MOVLW	NUMERO_2
	SUBWF	CUENTA_D,W
	BTFSS	STATUS,Z
	GOTO	MAYOR_15
	BSF	PORTA,2
	BCF	PORTA,1
MAYOR_15
	MOVLW	NUMERO
	SUBWF	CUENTA_D,W 
	BTFSS	STATUS,Z
	GOTO	START
	CLRF	CUENTA_D
	BSF	PORTA,1
	BCF	PORTA,2
	GOTO	START
	
DISPLAY
	ADDWF	PCL,F
	RETLW   3FH		;0
	RETLW   06H		;1
	RETLW   5BH		;2
	RETLW   4FH		;3
	RETLW   66H		;4
	RETLW   6DH		;5
	RETLW   7DH		;6
	RETLW   07H		;7
	RETLW   7FH		;8
	RETLW   67H		;9
	RETLW   77H		;A
	RETLW   7CH		;B
	RETLW   39H		;C
	RETLW   5EH		;D
	RETLW   79H		;E
	RETLW   71H		;F 

#include <Retardos.inc>	
	
	END
 
 
 